### ISSUE TITLE
Release v2.1.0

### ISSUE THREAD

**Issue by conradz** [reworkcss/css#50]
I think we should probably cut a new release soon. I don't think any of the changes are breaking changes, so we can just increment minor version.

Changes/Todo:
- [x] New error message format (#46)
- [x] `inputSourcemaps: false` to disable applying input source maps (#40)
- [x] Use `inherits` for inheritance (fixes browsers)
- [x] Unify test cases (#48)
- [x] Add `sourcemap: 'generator'` to return `SourceMapGenerator` object (#47)
- [x] #49
- [x] Update History.md
- [x] Update dependency versions
